### PR TITLE
ci: added build & test job 

### PR DESCRIPTION
**Pull request by saeidee**
- [X] Do only one thing
- [X] Non breaking API changes
- [X] Tested

### What did this pull request do?

We don't have any pipeline job to check if the project can run the build and successfully run the tests after any commit. We need to be sure that every commit is buildable and passes the tests.

### CODE REVIEW

**Comment by saeidee** [comment]
Currently, tests are failing in my machine as well, might be that it was broken a long time ago.

**Review by a631807682 — APPROVED** [review]
Are you interested in creating another PR to fix it？

**Comment by saeidee** [comment]
> Are you interested in creating another PR to fix it？

I will look into it 👍

**Comment by saeidee** [comment]
Shall we merge this PR and create another PR for test fixes?

**Comment by a631807682** [comment]
> Shall we merge this PR and create another PR for test fixes?

yes, from other PRs (https://github.com/go-gorm/mysql/pull/122/files), it seems that does not need to specify branches, you can confirm and merge it.

**Pull request merged**
